name: "Deriv App ID Generator action"
author: "Aaron Imming"
description: "Automatically generate App IDs for Deriv.app after feature branch has been deployed."
branding:
  icon: "code"
  color: "red"
inputs:
  DERIV_API_TOKEN:
    description: "The Deriv token to be used to generate App IDs. Please use a dedicated token. See https://app.deriv.com/account/api-token"
    required: true
  deriv_app_id:
    description: "The App ID to be used with Deriv API to identify the API connection to Deriv."
    required: true
  GITHUB_TOKEN:
    description: "The GitHub token to be used with Octokit to identify the API connection to GitHub."
    required: true
  max_retries:
    description: "Amount of times to retry generating an App ID"
    required: false
    default: 5
  vercel_preview_url:
    description: "The Vercel deployment URL to generate an App ID for."
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
